# Author: Marcos Antônio de Carvalho
# Descrição: Subir o stack de monitoramento (Prometheus e Grafana)
#
# Referências: https://aristides.dev/monitorando-seus-servidores-com-grafana-e-prometheus/
#

version: '3'

volumes:
  # volume para adicionar um datasource de forma automatizada assim que o serviço do Grafana subir. 
  # Usa o ds-prometheus.yaml dentro do diretório grafana_provisioning/Utiliza
  grafana_data:
  # volume do prometheus
  prometheus_data: 

# Criação da rede para o stack de monitoramento
# docker network create monitoring
networks:
  monitoring:
    external: true

services:

  # sistema de coleta de métricas de aplicações e serviços para armazenamento em um banco de dados de séries temporais.
  # PROMETHEUS vai consumir as metrica vindas do RABBITMQ
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    # automatically restarts the container - Docker daemon on restart or
    # the container itself is manually restarted
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_config:/prometheus_config # (mapeamento) arquivo de configuração
      - prometheus_data:/prometheus            # (volume) Banco de dados de serie temporais
    command:
      - "--config.file=/prometheus_config/prometheus.yaml" # arquivo de configuração 
      - "--storage.tsdb.path=/prometheus"       # Banco de dados de serie temporais
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - '--storage.tsdb.retention.time=360h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring      

  # sistema de DASHBOARD com visualizar em tempo real 
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    depends_on:
      - prometheus
    restart: always
    volumes:
      # (volume) banco de dados do Grafana com informações de usuários, configurações, dashboards, etc.
      - grafana_data:/var/lib/grafana  
      # (mapeamento) pasta de provisionamento onde definimos o datasource padrão que será 
      # usado pelo Grafana assim que ele iniciar
      - ./grafana_provisioning:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}      
    ports:
      - "3000:3000"
    networks:
      - monitoring      



